export type DiagnosticSeverity = "error" | "warning";

export interface Diagnostic {
  code: string;
  severity: DiagnosticSeverity;
  path: string;
  nodeId?: string;
  edgeIndex?: number;
  message: string;
  details?: unknown;
}

export interface ValidationResult {
  ok: boolean;
  diagnostics: Diagnostic[];
}

export const ERROR_CODES = {
  SCHEMA_INVALID: "WIR_SCHEMA_INVALID",
  DUPLICATE_NODE_ID: "WIR_DUPLICATE_NODE_ID",
  DUPLICATE_ARTIFACT_SCHEMA: "WIR_DUPLICATE_ARTIFACT_SCHEMA",
  DUPLICATE_VERIFIER_DEFINITION: "WIR_DUPLICATE_VERIFIER_DEFINITION",
  UNKNOWN_ARTIFACT_SCHEMA: "WIR_UNKNOWN_ARTIFACT_SCHEMA",
  INVALID_ARTIFACT_JSON_SCHEMA: "WIR_INVALID_ARTIFACT_JSON_SCHEMA",
  UNKNOWN_ENDPOINT: "WIR_UNKNOWN_ENDPOINT",
  REQUIRED_INPUT_MISSING_PRODUCER: "WIR_REQUIRED_INPUT_MISSING_PRODUCER",
  WORKFLOW_OUTPUT_MISSING_PRODUCER: "WIR_WORKFLOW_OUTPUT_MISSING_PRODUCER",
  MULTIPLE_PRODUCERS: "WIR_MULTIPLE_PRODUCERS",
  PORT_TYPE_MISMATCH: "WIR_PORT_TYPE_MISMATCH",
  FORBIDDEN_CYCLE: "WIR_FORBIDDEN_CYCLE",
  UNBOUNDED_LOOP: "WIR_UNBOUNDED_LOOP",
  UNREACHABLE_NODE: "WIR_UNREACHABLE_NODE",
  UNREACHABLE_OUTPUT: "WIR_UNREACHABLE_OUTPUT",
  WRITE_CONFLICT: "WIR_WRITE_CONFLICT",
  UNDECLARED_READ_CAPABILITY: "WIR_UNDECLARED_READ_CAPABILITY",
  UNDECLARED_WRITE_CAPABILITY: "WIR_UNDECLARED_WRITE_CAPABILITY",
  HIDDEN_VERIFIER_LEAKAGE: "WIR_HIDDEN_VERIFIER_LEAKAGE",
  AUTHORITY_OVERLAP: "WIR_AUTHORITY_OVERLAP",
  UNDECLARED_SECRET: "WIR_UNDECLARED_SECRET",
  UNDECLARED_NETWORK: "WIR_UNDECLARED_NETWORK",
  RETRY_BOUNDS: "WIR_RETRY_BOUNDS",
  TIMEOUT_BOUNDS: "WIR_TIMEOUT_BOUNDS",
  SIDE_EFFECT_GUARD_MISSING: "WIR_SIDE_EFFECT_GUARD_MISSING",
  RELEASE_VERIFIER_RULE: "WIR_RELEASE_VERIFIER_RULE",
  UNKNOWN_VERIFIER_REFERENCE: "WIR_UNKNOWN_VERIFIER_REFERENCE",
  BUDGET_EXCEEDED: "WIR_BUDGET_EXCEEDED"
} as const;
